### ISSUE TITLE
Conflict met PDC Elasticsearch plugin

### ISSUE THREAD

**Issue by richardkorthuis** [OpenWebconcept/plugin-pdc-leges#10]
**Beschrijf de bug**
De laatste versie van deze plugin geeft een foutmelding als deze is geïnstalleerd samen met de [PDC Elasticsearch plugin](https://github.com/OpenWebconcept/plugin-pdc-elasticsearch):

> Warning: Undefined array key "id" in wp-content\plugins\cmb2\includes\helper-functions.php on line 237
>
> Metabox configuration is required to have an ID parameter.

**Te reproduceren**
Stappen om het gedrag te reproduceren:
1. Installeer PDC Base, PDC Leges en PDC Elasticsearch (inclusief dependencies)
2. Activeer alle plugins
3. Zie fout

**Aanvullende context**
Downgraden naar versie 2.0.0 lost het probleem op. Het probleem is ontstaan toen PDC Leges is omgezet naar CMB2. Dit is voor PDC Elasticsearch nog niet gebeurd, waardoor er een CMB2 foutmelding wordt veroorzaakt.

**Comment by mvdhoek1** [comment]
Hi Richard,

Kun je eens boven [deze](https://github.com/OpenWebconcept/plugin-pdc-leges/blob/master/src/Leges/Settings/SettingsServiceProvider.php#L36) regel het volgende plaatsen om te testen? Bij mij gaat ie goed.

```
if (! isset($page['id'])) {
    return;
}
```

Dus:
```
protected function registerSettingsPage(array $page): void
{
	if (! isset($page['id'])) {
		return;
	}

	$fields = $page['fields'] ?? [];
	unset($page['fields']); // Fields will be added later.

	$optionsPage = \new_cmb2_box($page);

	if (empty($fields) || ! is_array($fields)) {
		return;
	}

	$this->registerSettingsPageFields($optionsPage, $fields);
}
```

Als ie bij jouw werkt voer ik hem morgen direct door.

**Comment by richardkorthuis** [comment]
Thanks het werkt!
